name: Deploy Backend

on: 
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to Backend EC2
        uses: appleboy/ssh-action@v0.1.10
        with: 
          host: ${{secrets.EC2_BACKEND_HOST}}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/Full_Stack_project
            git pull origin main
            docker stop backend || true
            docker rm backend || true
            docker rmi backend || true
            docker build -t backend -f backend/dockerfile backend/
            docker run -d -p 3000:3000 --name backend backend